name: smart_timetable
description: "Smart Timetable Generation using Flutter & Genetic Algorithm"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_analytics: ^11.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1  # 🔄 Updated to a compatible version
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
