name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # Ensure Flutter 3.13.0 with compatible Dart SDK

      # Force update Dart SDK
      - name: Install Dart SDK
        run: flutter doctor  # This checks and installs the necessary Dart SDK

      # Clear cache (important to avoid old SDK versions)
      - name: Clear Pub Cache
        run: flutter pub cache clean

      # Fetch dependencies
      - run: flutter pub get

      # Build web version
      - run: flutter build web

      # Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMART_TIMETABLE_GENERATION }}
          channelId: live
          projectId: smart-timetable-generation
